version: 0.0.0.{build}

# Build worker image (VM template)
image: Visual Studio 2019

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
  
# tasks
before_build:
- ps: ./.tools/discord/sendwebhook.ps1 start $env:WEBHOOK_URL
- cmd: .paket\paket.exe restore

build_script:
- cmd: >-
    ./build.bat

on_success:
  - ps: ./.tools/discord/sendwebhook.ps1 success $env:WEBHOOK_URL
on_failure:
  - ps: ./.tools/discord/sendwebhook.ps1 failure $env:WEBHOOK_URL

test: off

artifacts:
- path: publish\win-x86
  name: zKbProxy
- path: publish\linux-arm64
  name: zKbProxy-linux-arm64
- path: publish\ubuntu-x64
  name: zKbProxy-ubuntu-x64
- path: publish\ubuntu-arm64
  name: zKbProxy-ubuntu-arm64
