name: Build and Package

on:
  push:    
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore tools
      run: dotnet tool restore
    - name: Build
      run: dotnet fake run "build.fsx" -t All
    